# This script allows the PDF generated by a latex file to be automatically
# moved to another file after the document is compiledself.

# To use this script with TeXShop on a Mac, save this file to
# /usr/bin/python/Library/TeX/Root/bin/pdflatex.py and then go to
# TeXShop > Preferences > Engine and under pdfTex change both
# Tex and Latex to /usr/bin/python /Library/TeX/Root/bin/pdflatex.py.

# By default, the PDF will be in the same file as the .tex file.
# To change the directory add the comments below to the .tex file before
# the start of the document
# % pdflatex.py config
# % output dir = DIRNAME

# This script is modified from the code provided by macmadness86
# on the Mac OSX Hints forum: http://hints.macworld.com/article.php?story=20070906022746216

import os, sys, shutil, subprocess, re

pdf_path = "."

# Find the arguments from the Latex file.
with open(sys.argv[-1], 'r') as tex_file:
    line = tex_file.readline()
    while line != "" and re.search("\\\\begin{document}.*",line) == None:
        if re.search("%\s*pdflatex.py config",line) != None:
            # Find the directory the PDF should be moved to.
            pdf_match = re.search("\s*%\s*output dir\s*=\s*\S*", tex_file.readline())
            if pdf_match != None:
                pdf_path = re.sub("\s*%\s*output dir\s*=\s*","",pdf_match.string)
                pdf_path = re.sub("\n","",pdf_path)
                print "pdf path: " + pdf_path
        line = tex_file.readline()

# Setup variable to compile the Latex document
tex_file = sys.argv[-1]
pdf_file_name, extention = os.path.splitext(tex_file)

# Compile the Latex file
command = 'pdflatex --file-line-error --synctex=1' + ' ' + '"' + tex_file + '"'
os.system(command)

# Move the pdf
pdf_file_src = '%s%s' % (os.curdir, os.path.sep) + pdf_file_name + '.pdf'
pdf_file_dest = '%s%s' % (pdf_path, os.path.sep) + pdf_file_name + '.pdf'
print "src: " + pdf_file_src
print "dest: " + pdf_file_dest
try:
    shutil.move(pdf_file_src, pdf_file_dest)
except IOError:
    print '\n\nPDF file not found.'
